version: '3.1'

services:

  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    volumes:
            - ./databases:/var/lib/mysql

  adminer:
          build: ./adminer
          restart: always
          ports:
          - 6666:8080
