version: '3.1'

services:

  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 7777777
    volumes:
            - ./databases:/var/lib/mysql

  adminer:
          build: ./adminer
          restart: always
          ports:
          - 7878:8080
